
#include <GEL/Debug/Log.h>
#include <GEL/Core/DataBlock.h>

#include <fstream>
#include <string>
#include <GEL/Util/String/String.h>
using namespace std;

// TODO: Generate some accessable symbol that contains the size //

int main( int argc, char* argv[] ) {
	if ( argc < 3 ) {
		Log( "Text2CSharp - Convert a Text file to a C# file, and appends a null terminator (0)\n" );
		Log( "  Usage: Text2CSharp In.txt Out.cs PREFIX SUFFIX NAMESPACE CLASS\n" );
		return -1;
	}

	// Load File //
	DataBlock* File = new_DataBlock( argv[1] );
	
	string Prefix("");
	string Suffix("");
	string Namespace("");
	string Class("");
	
	if ( argc > 3 ) {
		Prefix = argv[3];
	}

	if ( argc > 4 ) {
		Suffix = argv[4];
	}
	
	if ( argc > 5 ) {
		Namespace = argv[5];
	}
	
	if ( argc > 6 ) {
		Class = argv[6];
	}
	
	string BaseName = String::BaseName( String::FileName( String::SystemSlash( argv[1] ) ) );
	string Symbol = Prefix + BaseName + Suffix;
	
	// Open Output File //
	ofstream Out( argv[2] );

	
	Out << "// " << Symbol << " - Generated by Text2CSharp //" << endl;
	if ( Namespace != "" ) {
		Out << "namespace " << Namespace << " {" << endl;
	}
	if ( Class != "" ) {
		Out << "\tpublic static partial class " << Class << " {" << endl;
	}
	Out << "\t\tpublic static sbyte[] " << Symbol << " = {";
	
	int NextLine = 0;
	for ( int idx = 0; idx < File->Size; idx++ ) {
		if ( NextLine-- == 0 ) {
			NextLine = 16;
			Out << "\n\t\t\t";			
		}
		
		if ( File->Data[idx] >= 32 )
			Out << "'" << (char)File->Data[idx] << "', ";
		else
			Out << (int)File->Data[idx] << ", ";
	}

	Out << "0";
	
	Out << endl << "\t\t};" << endl;
	if ( Class != "" ) {
		Out << "\t}" << endl;
	}
	if ( Namespace != "" ) {
		Out << "}" << endl;
	}
	
	
	// Close Output File //
	Out.close();
	
	// Done with File //
	delete_DataBlock(File);

	return 0;	
}
